# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://titenkov.github.io/
baseurl: /
title: Pavel Titenkov
author: Pavel Titenkov
description: Hi! I'm Pavel Titenkov - a full-stack engineer with a strong background in computer science
avatar: profile.png
email: pavel@titenkov.com
#social
facebook: pavel.titenkov
instagram: pavel.titenkov
github: titenkov
linkedin: titenkov
#twitter: username
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-37777266-2

# needed for travis-ci build
exclude: [vendor]
